In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('bls_occupation_allocc.csv')

In [4]:
df.columns = df.iloc[0]
df = df[1:]
df = df.reset_index(drop=True)

In [5]:
df

,2023 National Employment Matrix title,2023 National Employment Matrix code,Occupation type,"Employment, 2023","Employment, 2033","Employment distribution, percent, 2023","Employment distribution, percent, 2033","Employment change, numeric, 2023–33","Employment change, percent, 2023–33","Percent self employed, 2023","Occupational openings, 2023–33 annual average","Median annual wage, dollars, 2023[1]",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Related Occupational Outlook Handbook (OOH) content
0,"Total, all occupations",00-0000,Summary,"167,849.8","174,589.0",100.0,100.0,"6,739.2",4.0,5.8,"19,174.8","48,060",—,—,—,—
1,Management occupations,11-0000,Summary,"13,181.3","14,140.9",7.9,8.1,959.6,7.3,15.1,"1,160.0","116,880",—,—,—,—
2,Top executives,11-1000,Summary,"3,977.7","4,206.7",2.4,2.4,229.0,5.8,2.7,346.5,"103,460",—,—,—,—
3,Chief executives,11-1011,Line item,313.9,331.1,0.2,0.2,17.2,5.5,28.1,23.0,"206,680",Bachelor's degree,5 years or more,NaN,OOH Content
4,General and operations managers,11-1021,Line item,"3,630.1","3,840.5",2.2,2.2,210.4,5.8,0.5,320.8,"101,280",Bachelor's degree,5 years or more,NaN,OOH Content
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1112,"Material moving workers, all other",53-7199,Line item,26.5,27.6,0.0,0.0,1.2,4.4,6.8,3.0,"40,310",No formal educational credential,NaN,Short-term on-the-job training,—
1113,Footnotes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1114,[1] Data are from the Occupational Employment ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115,Note: Data is unavailable for values denoted w...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,"Source: Employment Projections program, U.S. B...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
major = df[df['Occupation type'] == 'Summary']

major = major[major['2023 National Employment Matrix code'].str[3] == '0']
major.loc[0, 'Occupation type'] = 'Total'
major

,2023 National Employment Matrix title,2023 National Employment Matrix code,Occupation type,"Employment, 2023","Employment, 2033","Employment distribution, percent, 2023","Employment distribution, percent, 2033","Employment change, numeric, 2023–33","Employment change, percent, 2023–33","Percent self employed, 2023","Occupational openings, 2023–33 annual average","Median annual wage, dollars, 2023[1]",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Related Occupational Outlook Handbook (OOH) content
0,"Total, all occupations",00-0000,Total,"167,849.8","174,589.0",100.0,100.0,"6,739.2",4.0,5.8,"19,174.8","48,060",—,—,—,—
1,Management occupations,11-0000,Summary,"13,181.3","14,140.9",7.9,8.1,959.6,7.3,15.1,"1,160.0","116,880",—,—,—,—
50,Business and financial operations occupations,13-0000,Summary,"10,977.2","11,738.5",6.5,6.7,761.3,6.9,4.1,963.5,"79,050",—,—,—,—
91,Computer and mathematical occupations,15-0000,Summary,"5,417.6","6,116.7",3.2,3.5,699.0,12.9,2.1,393.9,"104,200",—,—,—,—
119,Architecture and engineering occupations,17-0000,Summary,"2,639.7","2,819.7",1.6,1.6,180.0,6.8,2.3,195.0,"91,420",—,—,—,—
165,"Life, physical, and social science occupations",19-0000,Summary,"1,574.1","1,691.7",0.9,1.0,117.6,7.5,5.2,148.4,"78,280",—,—,—,—
231,Community and social service occupations,21-0000,Summary,"3,044.7","3,291.7",1.8,1.9,247.0,8.1,3.8,299.4,"52,000",—,—,—,—
254,Legal occupations,23-0000,Summary,"1,394.4","1,446.2",0.8,0.8,51.8,3.7,9.0,85.6,"99,220",—,—,—,—
268,Educational instruction and library occupations,25-0000,Summary,"9,579.9","9,731.2",5.7,5.6,151.3,1.6,1.7,868.0,"59,940",—,—,—,—
354,"Arts, design, entertainment, sports, and med...",27-0000,Summary,"3,073.1","3,203.2",1.8,1.8,130.1,4.2,26.0,306.3,"58,920",—,—,—,—
411,Healthcare practitioners and technical occup...,29-0000,Summary,"9,781.6","10,623.3",5.8,6.1,841.7,8.6,2.3,640.9,"80,820",—,—,—,—
496,Healthcare support occupations,31-0000,Summary,"7,516.9","8,659.3",4.5,5.0,"1,142.4",15.2,2.5,"1,261.1","36,140",—,—,—,—
521,Protective service occupations,33-0000,Summary,"3,630.7","3,704.7",2.2,2.1,74.0,2.0,0.2,419.3,"47,760",—,—,—,—
557,Food preparation and serving related occupat...,35-0000,Summary,"13,580.3","14,167.2",8.1,8.1,586.8,4.3,0.6,"2,683.4","32,240",—,—,—,—
580,Building and grounds cleaning and maintenanc...,37-0000,Summary,"5,640.5","5,817.4",3.4,3.3,176.9,3.1,12.0,786.8,"35,990",—,—,—,—
595,Personal care and service occupations,39-0000,Summary,"4,346.2","4,622.3",2.6,2.6,276.1,6.4,21.6,794.5,"34,260",—,—,—,—
643,Sales and related occupations,41-0000,Summary,"14,609.5","14,319.5",8.7,8.2,-290.0,-2.0,7.4,"1,817.3","36,760",—,—,—,—
676,Office and administrative support occupations,43-0000,Summary,"19,671.9","18,975.6",11.7,10.9,-696.3,-3.5,2.0,"2,073.7","44,480",—,—,—,—
741,"Farming, fishing, and forestry occupations",45-0000,Summary,982.9,964.5,0.6,0.6,-18.4,-1.9,8.2,145.2,"35,520",—,—,—,—
762,Construction and extraction occupations,47-0000,Summary,"7,338.3","7,752.3",4.4,4.4,414.0,5.6,13.9,663.5,"55,680",—,—,—,—
839,"Installation, maintenance, and repair occupa...",49-0000,Summary,"6,460.3","6,803.5",3.8,3.9,343.3,5.3,4.5,606.2,"53,920",—,—,—,—
906,Production occupations,51-0000,Summary,"9,093.6","8,999.5",5.4,5.2,-94.1,-1.0,2.9,970.1,"43,630",—,—,—,—
1046,Transportation and material moving occupations,53-0000,Summary,"14,315.1","15,000.1",8.5,8.6,685.1,4.8,3.9,"1,892.9","40,050",—,—,—,—

In [24]:
#df_majorocc = pd.read_csv('bls_occupation_majoroccgroup.csv')

In [25]:
# df_majorocc.columns = df_majorocc.iloc[0]
# df_majorocc = df_majorocc[1:24] # removes header and footnote rows
# df_majorocc = df_majorocc.reset_index(drop=True)

In [48]:
# df_majorocc

In [49]:
df_allocc = df[df['Occupation type'] == 'Line item']
df_allocc['Major Occupation Group Code'] = df_allocc['2023 National Employment Matrix code'].str[:2]

major_occupations = {'11': 'Management', '13': 'Business and Financial Operations', '15': 'Computer and Mathematics', '17': 'Architecture and Engineering', '19': 'Life, Physical, and Social Science', '21': 'Community and Social Services', '23':'Legal', '25':
 'Educational Instruction and Library', '27': 'Arts, Design, Entertainment, Sports, and Media', '29': 'Healthcare Practitioners and Technical', '31': 'Healthcare Support', '33': 'Protective Service', '35': 'Food Preparation and Serving', '37': 'Building and Grounds Cleaning and Maintenance', '39': 'Personal Care and Service', '41':'Sales',
  '43':'Office and Administrative Support', '45':'Farming, Fishing, and Forestry', 
  '47':'Construction and Extraction', '49':'Installation, Maintenance, and Repair', 
  '51':'Production', '53':'Transportation and Material Moving'}

df_allocc['Major Occupation Group'] = df_allocc['Major Occupation Group Code'].map(major_occupations)
df_allocc

/var/folders/3b/1r88wmn97dldhp05hd1q9b200000gn/T/ipykernel_16071/331048129.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_allocc['Major Occupation Group Code'] = df_allocc['2023 National Employment Matrix code'].str[:2]
/var/folders/3b/1r88wmn97dldhp05hd1q9b200000gn/T/ipykernel_16071/331048129.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_allocc['Major Occupation Group'] = df_allocc['Major Occupation Group Code'].map(major_occupations)

,2023 National Employment Matrix title,2023 National Employment Matrix code,Occupation type,"Employment, 2023","Employment, 2033","Employment distribution, percent, 2023","Employment distribution, percent, 2033","Employment change, numeric, 2023–33","Employment change, percent, 2023–33","Percent self employed, 2023","Occupational openings, 2023–33 annual average","Median annual wage, dollars, 2023[1]",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Related Occupational Outlook Handbook (OOH) content,Major Occupation Group Code,Major Occupation Group
3,Chief executives,11-1011,Line item,313.9,331.1,0.2,0.2,17.2,5.5,28.1,23.0,"206,680",Bachelor's degree,5 years or more,NaN,OOH Content,11,Management
4,General and operations managers,11-1021,Line item,"3,630.1","3,840.5",2.2,2.2,210.4,5.8,0.5,320.8,"101,280",Bachelor's degree,5 years or more,NaN,OOH Content,11,Management
5,Legislators,11-1031,Line item,33.7,35.0,0.0,0.0,1.4,4.1,—,2.7,"47,290",Bachelor's degree,Less than 5 years,NaN,—,11,Management
7,Advertising and promotions managers,11-2011,Line item,22.2,21.7,0.0,0.0,-0.6,-2.6,6.2,1.8,"131,870",Bachelor's degree,Less than 5 years,NaN,OOH Content,11,Management
9,Marketing managers,11-2021,Line item,389.1,420.8,0.2,0.2,31.7,8.2,3.2,34.8,"157,620",Bachelor's degree,5 years or more,NaN,OOH Content,11,Management
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1108,"Pump operators, except wellhead pumpers",53-7072,Line item,11.7,12.3,0.0,0.0,0.6,5.0,—,1.3,"54,690",High school diploma or equivalent,NaN,Moderate-term on-the-job training,—,53,Transportation and Material Moving
1109,Wellhead pumpers,53-7073,Line item,19.4,19.0,0.0,0.0,-0.4,-2.0,—,2.0,"71,830",High school diploma or equivalent,Less than 5 years,Moderate-term on-the-job training,—,53,Transportation and Material Moving
1110,Refuse and recyclable material collectors,53-7081,Line item,148.4,151.9,0.1,0.1,3.5,2.3,4.2,18.0,"45,760",No formal educational credential,NaN,Short-term on-the-job training,OOH Content,53,Transportation and Material Moving
1111,"Tank car, truck, and ship loaders",53-7121,Line item,12.7,13.2,0.0,0.0,0.5,3.9,7.2,1.4,"58,620",No formal educational credential,NaN,Short-term on-the-job training,—,53,Transportation and Material Moving
1112,"Material moving workers, all other",53-7199,Line item,26.5,27.6,0.0,0.0,1.2,4.4,6.8,3.0,"40,310",No formal educational credential,NaN,Short-term on-the-job training,—,53,Transportation and Material Moving

In [69]:
cleaned_data = pd.concat([major, df_allocc])
cleaned_data = cleaned_data.drop(columns=['Major Occupation Group Code', 'Related Occupational Outlook Handbook (OOH) content'])
cleaned_data = cleaned_data.reset_index(drop=True)
cleaned_data

,2023 National Employment Matrix title,2023 National Employment Matrix code,Occupation type,"Employment, 2023","Employment, 2033","Employment distribution, percent, 2023","Employment distribution, percent, 2033","Employment change, numeric, 2023–33","Employment change, percent, 2023–33","Percent self employed, 2023","Occupational openings, 2023–33 annual average","Median annual wage, dollars, 2023[1]",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Major Occupation Group
0,"Total, all occupations",00-0000,Total,"167,849.8","174,589.0",100.0,100.0,"6,739.2",4.0,5.8,"19,174.8","48,060",—,—,—,NaN
1,Management occupations,11-0000,Summary,"13,181.3","14,140.9",7.9,8.1,959.6,7.3,15.1,"1,160.0","116,880",—,—,—,NaN
2,Business and financial operations occupations,13-0000,Summary,"10,977.2","11,738.5",6.5,6.7,761.3,6.9,4.1,963.5,"79,050",—,—,—,NaN
3,Computer and mathematical occupations,15-0000,Summary,"5,417.6","6,116.7",3.2,3.5,699.0,12.9,2.1,393.9,"104,200",—,—,—,NaN
4,Architecture and engineering occupations,17-0000,Summary,"2,639.7","2,819.7",1.6,1.6,180.0,6.8,2.3,195.0,"91,420",—,—,—,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,"Pump operators, except wellhead pumpers",53-7072,Line item,11.7,12.3,0.0,0.0,0.6,5.0,—,1.3,"54,690",High school diploma or equivalent,NaN,Moderate-term on-the-job training,Transportation and Material Moving
851,Wellhead pumpers,53-7073,Line item,19.4,19.0,0.0,0.0,-0.4,-2.0,—,2.0,"71,830",High school diploma or equivalent,Less than 5 years,Moderate-term on-the-job training,Transportation and Material Moving
852,Refuse and recyclable material collectors,53-7081,Line item,148.4,151.9,0.1,0.1,3.5,2.3,4.2,18.0,"45,760",No formal educational credential,NaN,Short-term on-the-job training,Transportation and Material Moving
853,"Tank car, truck, and ship loaders",53-7121,Line item,12.7,13.2,0.0,0.0,0.5,3.9,7.2,1.4,"58,620",No formal educational credential,NaN,Short-term on-the-job training,Transportation and Material Moving
854,"Material moving workers, all other",53-7199,Line item,26.5,27.6,0.0,0.0,1.2,4.4,6.8,3.0,"40,310",No formal educational credential,NaN,Short-term on-the-job training,Transportation and Material Moving

In [76]:
cleaned_data['Employment, 2023'] = cleaned_data['Employment, 2023'].str.replace(',', '')
cleaned_data['Employment, 2033'] = cleaned_data['Employment, 2033'].str.replace(',', '')
cleaned_data['Employment change, numeric, 2023–33'] = cleaned_data['Employment change, numeric, 2023–33'].str.replace(',', '')
cleaned_data['Occupational openings, 2023–33 annual average'] = cleaned_data['Occupational openings, 2023–33 annual average'].str.replace(',', '')
cleaned_data['Median annual wage, dollars, 2023[1]'] = cleaned_data['Median annual wage, dollars, 2023[1]'].str.replace(',', '')

cleaned_data['Percent self employed, 2023'] = cleaned_data['Percent self employed, 2023'].str.replace('—', '0.0')
cleaned_data['Median annual wage, dollars, 2023[1]'] = cleaned_data['Median annual wage, dollars, 2023[1]'].str.replace('—', '0.0')
cleaned_data['Median annual wage, dollars, 2023[1]'] = cleaned_data['Median annual wage, dollars, 2023[1]'].str.replace('>=$239200', '239200.0')


cleaned_data

,2023 National Employment Matrix title,2023 National Employment Matrix code,Occupation type,"Employment, 2023","Employment, 2033","Employment distribution, percent, 2023","Employment distribution, percent, 2033","Employment change, numeric, 2023–33","Employment change, percent, 2023–33","Percent self employed, 2023","Occupational openings, 2023–33 annual average","Median annual wage, dollars, 2023[1]",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Major Occupation Group
0,"Total, all occupations",00-0000,Total,167849.8,174589.0,100.0,100.0,6739.2,4.0,5.8,19174.8,48060,—,—,—,NaN
1,Management occupations,11-0000,Summary,13181.3,14140.9,7.9,8.1,959.6,7.3,15.1,1160.0,116880,—,—,—,NaN
2,Business and financial operations occupations,13-0000,Summary,10977.2,11738.5,6.5,6.7,761.3,6.9,4.1,963.5,79050,—,—,—,NaN
3,Computer and mathematical occupations,15-0000,Summary,5417.6,6116.7,3.2,3.5,699.0,12.9,2.1,393.9,104200,—,—,—,NaN
4,Architecture and engineering occupations,17-0000,Summary,2639.7,2819.7,1.6,1.6,180.0,6.8,2.3,195.0,91420,—,—,—,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,"Pump operators, except wellhead pumpers",53-7072,Line item,11.7,12.3,0.0,0.0,0.6,5.0,0.0,1.3,54690,High school diploma or equivalent,NaN,Moderate-term on-the-job training,Transportation and Material Moving
851,Wellhead pumpers,53-7073,Line item,19.4,19.0,0.0,0.0,-0.4,-2.0,0.0,2.0,71830,High school diploma or equivalent,Less than 5 years,Moderate-term on-the-job training,Transportation and Material Moving
852,Refuse and recyclable material collectors,53-7081,Line item,148.4,151.9,0.1,0.1,3.5,2.3,4.2,18.0,45760,No formal educational credential,NaN,Short-term on-the-job training,Transportation and Material Moving
853,"Tank car, truck, and ship loaders",53-7121,Line item,12.7,13.2,0.0,0.0,0.5,3.9,7.2,1.4,58620,No formal educational credential,NaN,Short-term on-the-job training,Transportation and Material Moving
854,"Material moving workers, all other",53-7199,Line item,26.5,27.6,0.0,0.0,1.2,4.4,6.8,3.0,40310,No formal educational credential,NaN,Short-term on-the-job training,Transportation and Material Moving

In [77]:
convert_dict = {'Employment, 2023': float, 'Employment, 2033': float, 'Employment distribution, percent, 2023':float,
       'Employment distribution, percent, 2033':float,
       'Employment change, numeric, 2023–33':float,
       'Employment change, percent, 2023–33':float, 'Percent self employed, 2023':float,
       'Occupational openings, 2023–33 annual average':float,
       'Median annual wage, dollars, 2023[1]':float}

# Convert columns using the dictionary
cleaned_data= cleaned_data.astype(convert_dict)

In [81]:
cleaned_data['Percent self employed, 2023'] = cleaned_data['Percent self employed, 2023'].replace(0, None)
cleaned_data['Median annual wage, dollars, 2023[1]'] = cleaned_data['Median annual wage, dollars, 2023[1]'].replace(0, None)

In [82]:
cleaned_data

,2023 National Employment Matrix title,2023 National Employment Matrix code,Occupation type,"Employment, 2023","Employment, 2033","Employment distribution, percent, 2023","Employment distribution, percent, 2033","Employment change, numeric, 2023–33","Employment change, percent, 2023–33","Percent self employed, 2023","Occupational openings, 2023–33 annual average","Median annual wage, dollars, 2023[1]",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Major Occupation Group
0,"Total, all occupations",00-0000,Total,167849.8,174589.0,100.0,100.0,6739.2,4.0,5.8,19174.8,48060.0,—,—,—,NaN
1,Management occupations,11-0000,Summary,13181.3,14140.9,7.9,8.1,959.6,7.3,15.1,1160.0,116880.0,—,—,—,NaN
2,Business and financial operations occupations,13-0000,Summary,10977.2,11738.5,6.5,6.7,761.3,6.9,4.1,963.5,79050.0,—,—,—,NaN
3,Computer and mathematical occupations,15-0000,Summary,5417.6,6116.7,3.2,3.5,699.0,12.9,2.1,393.9,104200.0,—,—,—,NaN
4,Architecture and engineering occupations,17-0000,Summary,2639.7,2819.7,1.6,1.6,180.0,6.8,2.3,195.0,91420.0,—,—,—,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,"Pump operators, except wellhead pumpers",53-7072,Line item,11.7,12.3,0.0,0.0,0.6,5.0,None,1.3,54690.0,High school diploma or equivalent,NaN,Moderate-term on-the-job training,Transportation and Material Moving
851,Wellhead pumpers,53-7073,Line item,19.4,19.0,0.0,0.0,-0.4,-2.0,None,2.0,71830.0,High school diploma or equivalent,Less than 5 years,Moderate-term on-the-job training,Transportation and Material Moving
852,Refuse and recyclable material collectors,53-7081,Line item,148.4,151.9,0.1,0.1,3.5,2.3,4.2,18.0,45760.0,No formal educational credential,NaN,Short-term on-the-job training,Transportation and Material Moving
853,"Tank car, truck, and ship loaders",53-7121,Line item,12.7,13.2,0.0,0.0,0.5,3.9,7.2,1.4,58620.0,No formal educational credential,NaN,Short-term on-the-job training,Transportation and Material Moving
854,"Material moving workers, all other",53-7199,Line item,26.5,27.6,0.0,0.0,1.2,4.4,6.8,3.0,40310.0,No formal educational credential,NaN,Short-term on-the-job training,Transportation and Material Moving

In [84]:
cleaned_data[cleaned_data['Median annual wage, dollars, 2023[1]'].isna()]

,2023 National Employment Matrix title,2023 National Employment Matrix code,Occupation type,"Employment, 2023","Employment, 2033","Employment distribution, percent, 2023","Employment distribution, percent, 2033","Employment change, numeric, 2023–33","Employment change, percent, 2023–33","Percent self employed, 2023","Occupational openings, 2023–33 annual average","Median annual wage, dollars, 2023[1]",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Major Occupation Group
300,Actors,27-2011,Line item,76.0,79.5,0.0,0.0,3.5,4.5,17.1,8.6,None,"Some college, no degree",NaN,Long-term on-the-job training,"Arts, Design, Entertainment, Sports, and Media"
305,Dancers,27-2031,Line item,15.2,16.2,0.0,0.0,1.0,6.7,22.1,2.5,None,No formal educational credential,NaN,Long-term on-the-job training,"Arts, Design, Entertainment, Sports, and Media"
308,Musicians and singers,27-2042,Line item,169.3,172.8,0.1,0.1,3.5,2.1,52.6,20.4,None,No formal educational credential,NaN,Long-term on-the-job training,"Arts, Design, Entertainment, Sports, and Media"
309,"Disc jockeys, except radio",27-2091,Line item,21.0,22.1,0.0,0.0,1.1,5.1,65.6,2.0,None,High school diploma or equivalent,NaN,Short-term on-the-job training,"Arts, Design, Entertainment, Sports, and Media"
310,"Entertainers and performers, sports an...",27-2099,Line item,35.7,38.3,0.0,0.0,2.6,7.3,56.7,4.7,None,No formal educational credential,NaN,Short-term on-the-job training,"Arts, Design, Entertainment, Sports, and Media"
583,Fishing and hunting workers,45-3031,Line item,25.5,25.3,0.0,0.0,-0.2,-0.7,36.8,3.5,None,No formal educational credential,NaN,Moderate-term on-the-job training,"Farming, Fishing, and Forestry"

In [85]:
cleaned_data.to_csv('cleaned_bls_occupation.csv', index=False)